
- name: Disable default mysql module
  ansible.builtin.shell: dnf module disable mysql -y


- name: Copy mysql Repo file
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: Install MySQL
  ansible.builtin.yum:
    name : mysql-community-server
    state: installed

- name: Restart MySQL
  ansible.builtin.systemd:
    name: mysqld
    state: restarted
    enabled: yes

- name: Reset MySQL default password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass $root_mysql_password
  register: out #saving output to
  ignore_errors: yes

- name: password status
  ansible.builtin.debug:
    msg: password is already changed
  when: out.rc == 1



