- name: Copy mongoDB Repo file
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo
  when: schema_load

- name: Install MongoDB
  ansible.builtin.yum:
    name: mongodb-org-shell
    state: installed
  when: schema_load

- name: Load Schema
  community.mongodb.mongodb_shell:
    login_host: mongodb-dev.surendrak.online
    file: "/app/schema/{{component}}.js"
    idempotent: yes
  when: schema_load